--DOWN MIGRATIONS:
DROP TABLE IF EXISTS anime_genres;
DROP TABLE IF EXISTS anime_studios;
DROP TABLE IF EXISTS characters;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS studios;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS anime;
